### ISSUE TITLE
Saving generated wavetables using a full path name

### ISSUE THREAD

**Issue by faxinadu** [harveyormston/osc_gen#8]
I would like to be able to save the generated wavetable files into another path, in this case a sub directory of the working directory. When the name contains a full path, the script generates an error:
AttributeError: 'Wave_write' object has no attribute '_file'

doesn't work:
output_subdir = 'tables'
output_dir = os.getcwd() + '\\' + output_subdir
output_file_name = output_dir + '\\' + wt_name + "_" + str(wt_window_var) + "w_" + str(wt_size_var) + "s_" + str(wt_increment) + '.wav'

works:
output_file_name = wt_name + "_" + str(wt_window_var) + "w_" + str(wt_size_var) + "s_" + str(wt_increment) + '.wav'
		
wavfile.write_wavetable(wt_output, output_file_name)

**Comment by harveyormston** [comment]
This looks like file path delimiting weirdness on Windows to me. Possibly, the presence of `\` characters in the path name is causing some characters in the string to be escaped. It's generally safer to use `os.path.join()` for building up file paths. Also, `str.format()` is a bit nicer for building up strings out of variables.

Instead of:

```python
output_dir = os.getcwd() + '\' + output_subdir
output_file_name = output_dir + '\' + wt_name + "" + str(wt_window_var) + "w" + str(wt_size_var) + "s_" + str(wt_increment) + '.wav'
```

You could try something like:

```python
output_dir = os.path.join(os.getcwd(), output_subdir)
if not os.path.exists(output_dir):
    os.mkdir(output_dir)
output_file_name = "{}{}w{}s_{}.wav".format(wt_name, wt_window_var, wt_size_var, wt_increment)
output_file_path = os.path.join(output_dir, output_file_name)
```

**Comment by faxinadu** [comment]
great ! yes, doh of course :)
